parameters:
#    pogo_redis_entity.example.class: Pogotc\RedisEntityBundle\Example

services:
#    pogo_redis_entity.example:
#        class: %pogo_redis_entity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
